#!/usr/bin/env node
/* ============================================================
   STORIED — build
   ------------------------------------------------------------
   Run after any content or code change:   node build.js

   1. Regenerates packs/index.json from the pack files — the
      manifest is never edited by hand.
   2. Regenerates packs-bundle.js (every pack inlined) — used by
      the single-file standalone, file:// double-click, and tests.
   3. Builds storied-standalone.html with all CSS, JS, and packs
      inlined — send that one file to any phone.
   ============================================================ */

const fs = require("fs");
const path = require("path");

const read = (f) => fs.readFileSync(path.join(__dirname, f), "utf8");
const packsDir = path.join(__dirname, "packs");

/* ---------- 1. manifest ---------- */
const packs = {};
for (const file of fs.readdirSync(packsDir).filter((f) => f.endsWith(".json") && f !== "index.json")) {
  const data = JSON.parse(fs.readFileSync(path.join(packsDir, file), "utf8"));
  packs[data.id] = data;
}

const order = ["strangerthings"].concat(
  Object.keys(packs).filter((id) => id !== "core" && id !== "strangerthings").sort()
);

const index = {
  version: 1,
  packs: order.map((id) => {
    const p = packs[id];
    return {
      id: p.id, label: p.label, color: p.color, cta: p.cta,
      prompt: p.prompt, blurb: p.blurb, tags: p.tags || [],
      quoteCount: (p.quotes || []).length, loreCount: (p.lore || []).length
    };
  })
};
fs.writeFileSync(path.join(packsDir, "index.json"), JSON.stringify(index, null, 2));

/* ---------- 2. bundle ---------- */
const bundle = "/* generated by build.js — do not edit */\n" +
  "const PACKS_BUNDLE = " + JSON.stringify({ index, packs }) + ";\n";
fs.writeFileSync(path.join(__dirname, "packs-bundle.js"), bundle);

/* ---------- 3. standalone ---------- */
let html = read("index.html");
// NOTE: function replacements everywhere — inlined source can contain
// "$&"-style sequences that string replacements would reinterpret.
html = html.replace('<link rel="stylesheet" href="style.css">', () => "<style>\n" + read("style.css") + "\n</style>");
// the bundle must load before packstore.js so the eager path engages
html = html.replace('<script src="packcheck.js"></script>',
  () => "<script>\n" + read("packcheck.js") + "\n</script>");
html = html.replace('<script src="packstore.js"></script>',
  () => "<script>\n" + bundle + "\n</script>\n<script>\n" + read("packstore.js") + "\n</script>");
for (const script of ["strings.js", "motifs.js", "packcheck.js", "online.js", "achievements.js", "decks.js", "studio.js", "game.js"]) {
  html = html.replace(`<script src="${script}"></script>`, () => "<script>\n" + read(script) + "\n</script>");
}
if (/<script src="/.test(html) || /href="style/.test(html)) {
  console.error("build: an external reference was not inlined — check index.html");
  process.exit(1);
}
const out = path.join(__dirname, "storied-standalone.html");
fs.writeFileSync(out, html);
console.log(
  "manifest: " + index.packs.length + " packs \u00B7 bundle: " +
  (bundle.length / 1024).toFixed(1) + " KB \u00B7 standalone: " +
  (fs.statSync(out).size / 1024).toFixed(1) + " KB"
);

const dist = path.join(__dirname, "dist");

if (!fs.existsSync(dist)) {
    fs.mkdirSync(dist);
}

fs.copyFileSync(
    path.join(__dirname, "storied-standalone.html"),
    path.join(dist, "index.html")
);
